name: Trivy Scan
on:
  push:
    branches: [ '*' ]


jobs:
  Trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Scan
        run:  ./.github/trivy_scan.sh